spring:
  application:
    name: users

# Postgres sql db configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/devasee_users_db?IfExists=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 0

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: true

app:
  super-admin:
    email: npathumdilhara@gmail.com