spring:
  application:
    name: orders

  # Postgres sql db configuration
  datasource:
    url : jdbc:postgresql://db:5432/devasee_orders_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 0

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: true

security:
  internal-jwt:
    secret: ZGV2YXNlZS1lN2I4YzJkMS0xYjZmLTRlMWYtODhiMy05YTRmNWUxYTJjZGU=
