spring:
  application:
    name: promo

# Postgres sql db configuration
  datasource:
    url : jdbc:postgresql://db:5432/devasee_promo_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 0

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: true

security:
  internal-jwt:
    secret: ZGV2YXNlZS1lN2I4YzJkMS0xYjZmLTRlMWYtODhiMy05YTRmNWUxYTJjZGU=

azure:
  storage:
    # account-name: devaseebookstoreimages
    # account-key: YOUR_ACCOUNT_KEY
    # use the same connection string for all your containers in the same storage account.
    connect-str: DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=devaseebookstoreimages;AccountKey=pAjow61U0YsxPRwz+mZ+ihb3k4+KMrLHverA9Z4TY4nIwBS/MRjUDKUqD4EHQVGLhHmW2+/r/qGG+AStCiH9Kg==;BlobEndpoint=https://devaseebookstoreimages.blob.core.windows.net/;FileEndpoint=https://devaseebookstoreimages.file.core.windows.net/;QueueEndpoint=https://devaseebookstoreimages.queue.core.windows.net/;TableEndpoint=https://devaseebookstoreimages.table.core.windows.net/
