apiVersion: apps/v1
kind: Deployment
metadata:
  name: devasee-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devasee-db
  template:
    metadata:
      labels:
        app: devasee-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: db-init
          configMap:
            name: db-init-scripts
