spring:
  application:
    name: analytics

# Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/analytic_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


# JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true