spring:
  application:
    name: apigatgeway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product
              uri: lb://product
              predicates:
                - Path=/api/v1/product/**

            - id: promo
              uri: lb://promo
              predicates:
                - Path=/api/v1/promo/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
